global:
  scrape_interval: 15s
  external_labels:
    monitor: 'idk'

scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8185']
